/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package ProjectAssignment1;
import javax.persistence.*;

public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
	public static void main(String[] args) {
		
		EntityManagerFactory emf = Persistence.createEntityManagerFactory("a1Pu");
		EntityManager em =emf.createEntityManager();
		
		Person person = new Person();
		person.setPersonName("Ajay Kumar");
		person.setPersonEmail("Ajay1345@gmail.com");
		person.setPersonPhone(9848022335l);
		
		
		em.getTransaction().begin();
		em.persist(person);
		em.flush();
		em.getTransaction().commit();
		
	}
}
