/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package assignment2;

import javax.persistence.*;
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
    public static void main(String[] args) {
    	EntityManagerFactory emf = Persistence.createEntityManagerFactory("asgn2PU");
		EntityManager entitymanager = emf.createEntityManager();
		
		Address address = new Address();
		address.setCustomerAddress("dehradun");
		
		
		Customer cust = new Customer();
	    cust.setCustomerName("Manish");
	    cust.setCustomerEmail("qwerty@gmail.com");
	    cust.setCustomerAddress(address);
		
		entitymanager.getTransaction().begin();
		entitymanager.persist(cust);
		entitymanager.flush();
		entitymanager.getTransaction().commit();
		
		Customer mycust = entitymanager.find(Customer.class, "Manish");
		System.out.println(mycust.getCustomerName());
		System.out.println(mycust.getCustomerEmail());
		System.out.println(mycust.getCustomerAddress());
		
		
		
	}
}
